export default {
    notifyMSG: "Scroll Down Below To See some of the stuff I have been working on",
    notifyMSGTimeOut: 3000000,
    baseURL: "http://localhost:8080/",
    picSumBaseURL: "https://picsum.photos/id/",
    twitterIcon: "https://img.icons8.com/ios-glyphs/50/ffffff/twitter.png",
    linkedinIcon: "https://img.icons8.com/ios/48/ffffff/linkedin-filled.png",
    githubIcon: "https://img.icons8.com/ios-glyphs/48/ffffff/github.png",
    clipBoardPNG: "https://img.icons8.com/ios/48/000000/parse-from-clipboard.png",
    graduationCapPNG: "https://img.icons8.com/ios/48/000000/graduation-cap.png",
    gradInfo: "University of Ontario Institute of Technology : Graduated 2019",
    gradMajor: "Electrical Engineering - BEng",
    twitterLink: "https://twitter.com/AvaneesaBee",
    linkedInLink: "https://www.linkedin.com/in/avaneesa/",
    gitHubLink: "https://github.com/RedGhoul",
    blogLink: "https://www.somethingsblog.com/",
}
